import { test, expect } from "@playwright/test";

// Ensure to load environment variables before running tests
const baseUrl = process.env.BASE_URL;

test.describe("Theme Specifically Mobile Based", () => {
  let adminContext, adminPage;

  test.beforeAll(async ({ browser }) => {
    // Create a new browser context with admin storage state
    adminContext = await browser.newContext({ storageState: "playwright/.auth/admin.json" });
    adminPage = await adminContext.newPage();
  });


test('test', async ({ page }) => {

  await adminPage.goto("/wp-admin/admin.php?page=nx-dashboard");
  await page.locator('div').filter({ hasText: /^Add New$/ }).locator('a').click();
  await page.locator('#type_section').getByText('WooCommerce').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('.wprf-input-image').first().click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section').getByText('Reviews').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('.wprf-input-image').first().click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Growth Alert', { exact: true }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#themes').getByRole('img').nth(1).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('#type_section').getByText('Sales Notification').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('li').filter({ hasText: 'For Mobile' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.locator('div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('#themes > div:nth-child(2) > div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.locator('div:nth-child(3) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes > .wprf-section-fields > div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(4) > .wprf-input-radio-option > .wprf-input-label').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('li').filter({ hasText: /^Source$/ }).getByRole('img').click();
  await page.locator('div:nth-child(5) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('li').filter({ hasText: 'For Mobile' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section > .wprf-section-fields > .wprf-control-wrapper > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(6) > .wprf-input-radio-option > .wprf-input-label').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('li').filter({ hasText: 'For Desktop' }).click();
  await page.locator('#themes > div:nth-child(2) > div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.locator('div:nth-child(7) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();


  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Cookie Notice').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('div').filter({ hasText: /^Select ThemeLightDark$/ }).locator('label').nth(1).click();
  await page.locator('div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.getByText('eLearning', { exact: true }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes').getByRole('img').nth(1).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).getByRole('img').click();
  await page.locator('#source_section').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('#themes > div:nth-child(2) > div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section').getByRole('img').nth(2).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes').getByRole('img').first().click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Notification Bar').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#themes').getByRole('img').nth(1).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('#type_section').getByText('Reviews').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('#themes > div:nth-child(2) > div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(4) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('div:nth-child(3) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('div:nth-child(4) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('div:nth-child(5) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  
  
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.locator('div:nth-child(6) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Contact Form').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes').getByRole('img').nth(1).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.getByText('WPForms', { exact: true }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('#themes').getByRole('img').nth(3).click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Ninja Forms').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes').getByRole('img').first().click();
  await page.locator('li').filter({ hasText: /^Source$/ }).getByRole('img').click();
  await page.getByText('Fluent Forms').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('li').filter({ hasText: 'For Desktop' }).click();
  await page.locator('#themes').getByRole('img').nth(3).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Gravity Forms').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('li').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes').getByRole('img').nth(1).click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Elementor Form').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('#themes').getByRole('img').nth(3).click();
  await page.locator('#themes').getByRole('img').nth(4).click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Download Stats').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('li').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes label').nth(1).click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('li').filter({ hasText: 'For Desktop' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Comments', { exact: true }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes').getByRole('img').nth(4).click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Discount Alert').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('ul').filter({ hasText: 'For Desktop' }).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).locator('path').click();
 
  await page.locator('li').filter({ hasText: /^Source$/ }).getByRole('img').click();
  await page.getByText('Donations', { exact: true }).click();
  await page.locator('#source_section').getByRole('img').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label').click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Flashing Tab').click();
  await page.locator('#source_section').getByText('Flashing Tab').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#themes').getByRole('img').nth(2).click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Growth Alert 🚀').click();
  await page.locator('#source_section').getByRole('img').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('ul').filter({ hasText: 'For Desktop' }).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('ul').filter({ hasText: 'For Desktop' }).click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section label').nth(2).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('ul').filter({ hasText: 'For Desktop' }).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section').getByRole('img').nth(3).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('ul').filter({ hasText: 'For Desktop' }).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section').getByRole('img').nth(4).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('ul').filter({ hasText: 'For Desktop' }).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Custom Notification').click();
  await page.locator('#source_section label').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('ul').filter({ hasText: 'For Desktop' }).click();
  await page.locator('ul').filter({ hasText: 'For Desktop' }).click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Video', { exact: true }).click();
  await page.locator('#source_section label').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label').click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Email Subscription').click();
  await page.locator('#source_section').getByRole('img').first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes').getByRole('img').nth(1).click();
  await page.locator('li').filter({ hasText: /^Source$/ }).locator('path').click();
  
  
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section').getByRole('img').nth(1).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('#themes > div:nth-child(2) > div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.locator('#source_section label').nth(2).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('li').filter({ hasText: 'For Mobile' }).click();
  await page.locator('#responsive_themes').getByRole('img').first().click();
  await page.locator('li').filter({ hasText: /^Source$/ }).getByRole('img').click();
  await page.locator('#source_section').getByRole('img').nth(3).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('span').filter({ hasText: 'For Desktop' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').click();
  await page.locator('span').filter({ hasText: /^Source$/ }).click();
  await page.getByText('Page Analytics').click();
  await page.locator('#source_section').getByRole('img').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#themes > div:nth-child(2) > div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div > .wprf-input-radio-option > .wprf-input-label > .wprf-input-image').first().click();
  await page.locator('span').filter({ hasText: 'For Mobile' }).click();
  await page.locator('div:nth-child(2) > .wprf-control-field > .wprf-control > .wprf-row > div:nth-child(2) > .wprf-input-radio-option > .wprf-input-label').first().click();
});

});